### ISSUE TITLE
General form of secrets.js

### ISSUE THREAD

**Issue by mciantyre** [wakatime/slack-demo-chat#1]
Would you be able to provide the general form of your secrets.js file? `secrets.announce_presence` and `secrets.users` in particular.

My student team and I have been looking for a Slack chat portal for our club members to provide us anonymous feedback. Your demo chat is very helpful. Thanks for sharing!

**Comment by alanhamlett** [comment]
Sure:

``` JavaScript
module.exports = {
  slack_token: '',
  slack_channel: '',
  command_token: '',
  http_port: 8080,
  https_port: 8081,
};
```

You should create a slack [slash command](https://wakatime.slack.com/services/new/slash-commands) with:
command: `/r`
url: `https://host:8081/webhooks/slack`
method: `POST`
token: [same as `slack_token` in secrets

Then to reply to a visitor use your slash command with the visitor's unique id inside slack:
`/r xu3sdf hello`
